<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="navbar_style.css">
    
</head>

<body>
    <div class="nav-wrapper">
    <div class="topnav" id="theTopNav">
        <a href="./home.php">HOME</a>
        <a href="./contact.php">CONTACT</a>
        
    </div>
    </div>



</body>
</html>
